// GPU-evaluated 2D fields. This text is appended to render.wgsl (Camera/Frame) and to the
// per-field `field_fn(v0: f32, v1: f32) -> f32` module (or, for domain colouring, a module
// defining `field_color(x, y) -> vec4<f32>`) (PRELUDE + function) generated by
// math_core::wgsl, so one pipeline is compiled per distinct expression.
//
// PRECISION: the quad's xy is origin-relative (small), and the per-field origin is added back
// in f32 just before `field_fn`, which itself is f32. Near the origin this is exact enough; at
// deep zoom far from 0 (window span below ~1e-5 of |origin|) the absolute coordinate runs out
// of f32 mantissa and the field shows banding/blockiness. The CPU contour (f64) stays exact.

struct FieldParams {
    color: vec4<f32>,
    rect_min: vec2<f32>,
    rect_max: vec2<f32>,
    origin: vec2<f32>,
    // 0 = hue field, 1 = fill where f > 0, 2 = fill where f < 0 (3 = domain colouring)
    kind: f32,
    _pad: f32,
    // Slider values for this field (index i is params[i / 4][i % 4]); the generated wrapper
    // `field_fn` / `field_color` reads them, so the shader text does not depend on the values.
    params: array<vec4<f32>, 4>,
};

@group(1) @binding(0) var<uniform> fp: FieldParams;

struct FieldOut {
    @builtin(position) pos: vec4<f32>,
    @location(0) w: vec2<f32>,
};

@vertex
fn vs_field(@builtin(vertex_index) vi: u32) -> FieldOut {
    var corners = array<vec2<f32>, 6>(
        vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0), vec2<f32>(1.0, 1.0),
        vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 1.0), vec2<f32>(0.0, 1.0),
    );
    let w = mix(fp.rect_min, fp.rect_max, corners[vi]);
    var out: FieldOut;
    out.pos = cam.view_proj * vec4<f32>(placed(vec3<f32>(w, 0.0)), 1.0);
    out.w = w;
    return out;
}

fn hsv2rgb(h: f32, s: f32, v: f32) -> vec3<f32> {
    let k = vec3<f32>(1.0, 2.0 / 3.0, 1.0 / 3.0);
    let p = abs(fract(vec3<f32>(h) + k) * 6.0 - vec3<f32>(3.0));
    return v * mix(vec3<f32>(1.0), clamp(p - vec3<f32>(1.0), vec3<f32>(0.0), vec3<f32>(1.0)), s);
}

// ==== fs_field ====
@fragment
fn fs_field(in: FieldOut) -> @location(0) vec4<f32> {
    let p = fp.origin + in.w;
    let v = field_fn(p.x, p.y);
    // Derivatives first, while control flow is still uniform.
    let fw = fwidth(v);
    // Squash to a signed log scale: s = sign(v) * ln(1 + |v|). One full hue cycle spans 2.0 of
    // s (|v| ~ 6.4), so [-1, 1] covers ~70% of the wheel and big values wrap slowly.
    let s = sign(v) * log(1.0 + abs(v));
    let u = s * 0.5;
    let gu = fwidth(u);

    let finite = (v == v) && (abs(v) < 3.0e38);
    var rgb = fp.color.rgb;
    var alpha = 0.0;
    if (fp.kind < 0.5) {
        // Hue ramp, desaturated where the value changes fast per pixel (steep / poles), so
        // aliased rainbow noise fades to a calm grey-white instead.
        let hue = fract(u + 0.62);
        let sat = 0.85 / (1.0 + 8.0 * gu);
        rgb = hsv2rgb(hue, sat, 0.96);
        alpha = 0.9 * fp.color.a;
    } else {
        // Signed distance in pixels (positive inside) from the value and its screen gradient;
        // coverage ramps over one pixel for an anti-aliased edge.
        let sgn = select(-1.0, 1.0, fp.kind < 1.5);
        let d = v * sgn / max(fw, 1.0e-20);
        alpha = 0.22 * fp.color.a * clamp(d + 0.5, 0.0, 1.0);
    }
    alpha = alpha * frame.fade;
    // Invisible fragments are skipped like in the other pipelines.
    if (!finite || alpha < 0.01) {
        discard;
    }
    return vec4<f32>(rgb, alpha);
}

// ==== fs_domain ====
@fragment
fn fs_domain(in: FieldOut) -> @location(0) vec4<f32> {
    let p = fp.origin + in.w;
    let c = field_color(p.x, p.y);
    let alpha = c.a * fp.color.a * frame.fade;
    if (alpha < 0.01) {
        discard;
    }
    return vec4<f32>(c.rgb, alpha);
}
